def MSA_3D_assemble_global_linear_elastic_stiffness_CC0_H2_T3(node_coords, elements):
    n_nodes = node_coords.shape[0]
    K = np.zeros((6 * n_nodes, 6 * n_nodes))
    for elem in elements:
        i = elem['node_i']
        j = elem['node_j']
        E = elem['E']
        nu = elem['nu']
        A = elem['A']
        I_y = elem['I_y']
        I_z = elem['I_z']
        J = elem['J']
        local_z = elem.get('local_z')
        (xi, yi, zi) = node_coords[i]
        (xj, yj, zj) = node_coords[j]
        L_vec = np.array([xj - xi, yj - yi, zj - zi])
        L = np.linalg.norm(L_vec)
        if L == 0:
            continue
        L_hat = L_vec / L
        if local_z is None:
            if abs(L_hat[2]) < 0.999:
                local_z_guess = np.array([0.0, 0.0, 1.0])
            else:
                local_z_guess = np.array([0.0, 1.0, 0.0])
            local_z = local_z_guess - np.dot(local_z_guess, L_hat) * L_hat
            if np.linalg.norm(local_z) < 1e-10:
                local_z_guess = np.array([0.0, 1.0, 0.0])
                local_z = local_z_guess - np.dot(local_z_guess, L_hat) * L_hat
                if np.linalg.norm(local_z) < 1e-10:
                    local_z_guess = np.array([1.0, 0.0, 0.0])
                    local_z = local_z_guess - np.dot(local_z_guess, L_hat) * L_hat
            local_z = local_z / np.linalg.norm(local_z)
        else:
            local_z = np.array(local_z, dtype=float)
            local_z = local_z / np.linalg.norm(local_z)
            proj = np.dot(local_z, L_hat)
            local_z = local_z - proj * L_hat
            if np.linalg.norm(local_z) < 1e-10:
                raise ValueError('local_z vector is parallel to beam axis')
            local_z = local_z / np.linalg.norm(local_z)
        local_y = np.cross(L_hat, local_z)
        local_y = local_y / np.linalg.norm(local_y)
        R = np.zeros((3, 3))
        R[:, 0] = L_hat
        R[:, 1] = local_y
        R[:, 2] = local_z
        Gamma = np.zeros((12, 12))
        for k in range(3):
            Gamma[k, k] = R[0, 0]
            Gamma[k, k + 3] = R[0, 1]
            Gamma[k, k + 6] = R[0, 2]
            Gamma[k + 3, k] = R[1, 0]
            Gamma[k + 3, k + 3] = R[1, 1]
            Gamma[k + 3, k + 6] = R[1, 2]
            Gamma[k + 6, k] = R[2, 0]
            Gamma[k + 6, k + 3] = R[2, 1]
            Gamma[k + 6, k + 6] = R[2, 2]
            Gamma[k + 9, k] = R[0, 0]
            Gamma[k + 9, k + 3] = R[0, 1]
            Gamma[k + 9, k + 6] = R[0, 2]
            Gamma[k + 12, k] = R[1, 0]
            Gamma[k + 12, k + 3] = R[1, 1]
            Gamma[k + 12, k + 6] = R[1, 2]
            Gamma[k + 15, k] = R[2, 0]
            Gamma[k + 15, k + 3] = R[2, 1]
            Gamma[k + 15, k + 6] = R[2, 2]
        Gamma = np.zeros((12, 12))
        for r in range(3):
            for c in range(3):
                Gamma[r, c] = R[r, c]
                Gamma[r + 3, c + 3] = R[r, c]
                Gamma[r + 6, c] = R[r, c]
                Gamma[r + 9, c + 3] = R[r, c]
        k_local = np.zeros((12, 12))
        k_axial = E * A / L
        k_by = E * I_y / L ** 3
        k_bz = E * I_z / L ** 3
        k_tors = E * J / (2 * (1 + nu)) / L
        k_local[0, 0] = k_axial
        k_local[0, 6] = -k_axial
        k_local[6, 0] = -k_axial
        k_local[6, 6] = k_axial
        k_local[1, 1] = 12 * k_bz
        k_local[1, 2] = 0
        k_local[1, 4] = -6 * k_bz * L
        k_local[1, 7] = -12 * k_bz
        k_local[1, 8] = 0
        k_local[1, 10] = -6 * k_bz * L
        k_local[2, 1] = 0
        k_local[2, 2] = 12 * k_by
        k_local[2, 4] = 0
        k_local[2, 7] = 0
        k_local[2, 8] = -6 * k_by * L
        k_local[2, 10] = 0
        k_local[4, 1] = -6 * k_bz * L
        k_local[4, 2] = 0
        k_local[4, 4] = 4 * k_bz * L ** 2
        k_local[4, 7] = 6 * k_bz * L
        k_local[4, 8] = 0
        k_local[4, 10] = 2 * k_bz * L ** 2
        k_local[7, 1] = -12 * k_bz
        k_local[7, 2] = 0
        k_local[7, 4] = 6 * k_bz * L
        k_local[7, 7] = 12 * k_bz
        k_local[7, 8] = 0
        k_local[7, 10] = 6 * k_bz * L
        k_local[8, 1] = 0
        k_local[8, 2] = -6 * k_by * L
        k_local[8, 4] = 0
        k_local[8, 7] = 0
        k_local[8, 8] = 4 * k_by * L ** 2
        k_local[8, 10] = 0
        k_local[10, 1] = -6 * k_bz * L
        k_local[10, 2] = 0
        k_local[10, 4] = 2 * k_bz * L ** 2
        k_local[10, 7] = 6 * k_bz * L
        k_local[10, 8] = 0
        k_local[10, 10] = 4 * k_bz * L ** 2
        k_local[3, 3] = k_tors
        k_local[3, 9] = -k_tors
        k_local[9, 3] = -k_tors
        k_local[9, 9] = k_tors
        k_local = np.zeros((12, 12))
        k_local[0, 0] = k_axial
        k_local[0, 6] = -k_axial
        k_local[6, 0] = -k_axial
        k_local[6, 6] = k_axial
        k_local[3, 3] = k_tors
        k_local[3, 9] = -k_tors
        k_local[9, 3] = -k_tors
        k_local[9, 9] = k_tors
        k_local[1, 1] = 12 * k_bz
        k_local[1, 2] = 0
        k_local[1, 4] = -6 * k_bz * L
        k_local[1, 7] = -12 * k_bz
        k_local[1, 8] = 0
        k_local[1, 10] = -6 * k_bz * L
        k_local[2, 1] = 0
        k_local[2, 2] = 12 * k_by
        k_local[2, 4] = 0
        k_local[2, 7] = 0
        k_local[2, 8] = -6 * k_by * L
        k_local[2, 10] = 0
        k_local[4, 1] = -6 * k_bz * L
        k_local[4, 2] = 0
        k_local[4, 4] = 4 * k_bz * L ** 2
        k_local[4, 7] = 6 * k_bz * L
        k_local[4, 8] = 0
        k_local[4, 10] = 2 * k_bz * L ** 2
        k_local[7, 1] = -12 * k_bz
        k_local[7, 2] = 0
        k_local[7, 4] = 6 * k_bz * L
        k_local[7, 7] = 12 * k_bz
        k_local[7, 8] = 0
        k_local[7, 10] = 6 * k_bz * L
        k_local[8, 1] = 0
        k_local[8, 2] = -6 * k_by * L
        k_local[8, 4] = 0
        k_local[8, 7] = 0
        k_local[8, 8] = 4 * k_by * L ** 2
        k_local[8, 10] = 0
        k_local[10, 1] = -6 * k_bz * L
        k_local[10, 2] = 0
        k_local[10, 4] = 2 * k_bz * L ** 2
        k_local[10, 7] = 6 * k_bz * L
        k_local[10, 8] = 0
        k_local[10, 10] = 4 * k_bz * L ** 2
        k_local[1, 1] += 12 * k_by
        k_local[1, 5] = -6 * k_by * L
        k_local[1, 7] += -12 * k_by
        k_local[1, 11] = -6 * k_by * L
        k_local[2, 5] = 0
        k_local[2, 8] += 12 * k_bz
        k_local[2, 11] = 0
        k_local[5, 1] = -6 * k_by * L
        k_local[5, 2] = 0
        k_local[5, 5] = 4 * k_by * L ** 2
        k_local[5, 7] = 6 * k_by * L
        k_local[5, 8] = 0
        k_local[5, 11] = 2 * k_by * L ** 2
        k_local[7, 1] += -12 * k_by
        k_local[7, 5] = 6 * k_by * L
        k_local[7, 7] += 12 * k_by
        k_local[7, 11] = 6 * k_by * L
        k_local[8, 5] = 0
        k_local[8, 8] += 4 * k_bz
        k_local[8, 11] = 0
        k_local[11, 1] = -6 * k_by * L
        k_local[11, 2] = 0
        k_local[11, 5] = 2 * k_by * L ** 2
        k_local[11, 7] = 6 * k_by * L
        k_local[11, 8] = 0
        k_local[11, 11] = 4 * k_by * L ** 2
        k_local = np.zeros((12, 12))
        k_local[0, 0] = k_axial
        k_local[0, 6] = -k_axial
        k_local[6, 0] = -k_axial
        k_local[6, 6] = k_axial
        k_local[3, 3] = k_tors
        k_local[3, 9] = -k_tors
        k_local[9, 3] = -k_tors
        k_local[9, 9] = k_tors
        k_local[1, 1] = 12 * k_by
        k_local[1, 2] = 0
        k_local[1, 4] = -6 * k_by * L
        k_local[1, 7] = -12 * k_by
        k_local[1, 8] = 0
        k_local[1, 10] = -6 * k_by * L
        k_local[2, 1] = 0
        k_local[2, 2] = 12 * k_bz
        k_local[2, 4] = -6 * k_bz * L
        k_local[2, 7] = 0
        k_local[2, 8] = -12 * k_bz
        k_local[2, 10] = -6 * k_bz * L
        k_local[4, 1] = -6 * k_by * L
        k_local[4, 2] = -6 * k_bz * L
        k_local[4, 4] = 4 * k_by * L ** 2
        k_local[4, 7] = 6 * k_by * L
        k_local[4, 8] = 6 * k_bz * L
        k_local[4, 10] = 2 * k_by * L ** 2
        k_local[7, 1] = -12 * k_by
        k_local[7, 2] = 0
        k_local[7, 4] = 6 * k_by * L
        k_local[7, 7] = 12 * k_by
        k_local[7, 8] = 0
        k_local[7, 10] = 6 * k_by * L
        k_local[8, 1] = 0
        k_local[8, 2] = -12 * k_bz
        k_local[8, 4] = 6 * k_bz * L
        k_local[8, 7] = 0
        k_local[8, 8] = 12 * k_bz
        k_local[8, 10] = 6 * k_bz * L
        k_local[10, 1] = -6 * k_by * L
        k_local[10, 2] = -6 * k_bz * L
        k_local[10, 4] = 2 * k_by * L ** 2
        k_local[10, 7] = 6 * k_by * L
        k_local[10, 8] = 6 * k_bz * L
        k_local[10, 10] = 4 * k_by * L ** 2
        K_elem = Gamma.T @ k_local @ Gamma
        dof_map = [6 * i, 6 * i + 1, 6 * i + 2, 6 * i + 3, 6 * i + 4, 6 * i + 5, 6 * j, 6 * j + 1, 6 * j + 2, 6 * j + 3, 6 * j + 4, 6 * j + 5]
        for a in range(12):
            for b in range(12):
                K[dof_map[a], dof_map[b]] += K_elem[a, b]
    return K